export const USER_ROLE = {
  admin: "admin",
  user: "user",
};

export const foodCategories = [
  { label: "Formula Milk", value: "Formula Milk" },
  { label: "Cereal", value: "Cereal" },
  { label: "Snacks", value: "Snacks" },
  { label: "Purees", value: "Purees" },
  { label: "Drinks", value: "Drinks" },
  { label: "Supplements", value: "Supplements" },
  { label: "Teething Biscuits", value: "Teething Biscuits" },
  { label: "Finger Foods", value: "Finger Foods" },
  { label: "Jar Foods", value: "Jar Foods" },
  { label: "Organic Food", value: "Organic Food" },
  { label: "Gluten-Free Food", value: "Gluten-Free Food" },
  { label: "Dairy-Free Food", value: "Dairy-Free Food" },
  { label: "Food Pouches", value: "Food Pouches" },
  { label: "Food Jars", value: "Food Jars" },
  { label: "Food Puffs", value: "Food Puffs" },
  { label: "Rice Cakes", value: "Rice Cakes" },
  { label: "Yogurt", value: "Yogurt" },
  { label: "Fruit Pouches", value: "Fruit Pouches" },
  { label: "Vegetable Pouches", value: "Vegetable Pouches" },
  { label: "Homemade Food", value: "Homemade Food" },
];

export const vitamins = [
  { value: "vitaminA", label: "Vitamin A" },
  { value: "vitaminD", label: "Vitamin D" },
  { value: "vitaminE", label: "Vitamin E" },
  { value: "vitaminK", label: "Vitamin K" },
  { value: "vitaminC", label: "Vitamin C" },
  { value: "vitaminB1", label: "Vitamin B1 (Thiamine)" },
  { value: "vitaminB2", label: "Vitamin B2 (Riboflavin)" },
  { value: "vitaminB3", label: "Vitamin B3 (Niacin)" },
  { value: "vitaminB6", label: "Vitamin B6" },
  { value: "vitaminB12", label: "Vitamin B12" },
  { value: "folate", label: "Folate (Vitamin B9)" },
  { value: "pantothenicAcid", label: "Pantothenic Acid (Vitamin B5)" },
  { value: "biotin", label: "Biotin (Vitamin B7)" },
];

export const Minerals = [
  { value: "Calcium", label: "Calcium" },
  { value: "Iron", label: "Iron" },
  { value: "Zinc", label: "Zinc" },
  { value: "Magnesium", label: "Magnesium" },
  { value: "Phosphorus", label: "Phosphorus" },
  { value: "Potassium", label: "Potassium" },
  { value: "Selenium", label: "Selenium" },
  { value: "Copper", label: "Copper" },
  { value: "Iodine", label: "Iodine" },
  { value: "Manganese", label: "Manganese" },
];

export const District = [
  { label: "Bagerhat", value: "Bagerhat" },
  { label: "Bandarban", value: "Bandarban" },
  { label: "Barguna", value: "Barguna" },
  { label: "Barisal", value: "Barisal" },
  { label: "Bhola", value: "Bhola" },
  { label: "Bogra", value: "Bogra" },
  { label: "Brahmanbaria", value: "Brahmanbaria" },
  { label: "Chandpur", value: "Chandpur" },
  { label: "Chapainawabganj", value: "Chapainawabganj" },
  { label: "Chittagong", value: "Chittagong" },
  { label: "Chuadanga", value: "Chuadanga" },
  { label: "Comilla", value: "Comilla" },
  { label: "Cox's Bazar", value: "Cox's Bazar" },
  { label: "Dhaka", value: "Dhaka" },
  { label: "Dinajpur", value: "Dinajpur" },
  { label: "Faridpur", value: "Faridpur" },
  { label: "Feni", value: "Feni" },
  { label: "Gaibandha", value: "Gaibandha" },
  { label: "Gazipur", value: "Gazipur" },
  { label: "Gopalganj", value: "Gopalganj" },
  { label: "Habiganj", value: "Habiganj" },
  { label: "Jamalpur", value: "Jamalpur" },
  { label: "Jessore", value: "Jessore" },
  { label: "Jhalokati", value: "Jhalokati" },
  { label: "Jhenaidah", value: "Jhenaidah" },
  { label: "Joypurhat", value: "Joypurhat" },
  { label: "Khagrachhari", value: "Khagrachhari" },
  { label: "Khulna", value: "Khulna" },
  { label: "Kishoreganj", value: "Kishoreganj" },
  { label: "Kurigram", value: "Kurigram" },
  { label: "Kushtia", value: "Kushtia" },
  { label: "Lakshmipur", value: "Lakshmipur" },
  { label: "Lalmonirhat", value: "Lalmonirhat" },
  { label: "Madaripur", value: "Madaripur" },
  { label: "Magura", value: "Magura" },
  { label: "Manikganj", value: "Manikganj" },
  { label: "Meherpur", value: "Meherpur" },
  { label: "Moulvibazar", value: "Moulvibazar" },
  { label: "Munshiganj", value: "Munshiganj" },
  { label: "Mymensingh", value: "Mymensingh" },
  { label: "Naogaon", value: "Naogaon" },
  { label: "Narail", value: "Narail" },
  { label: "Narayanganj", value: "Narayanganj" },
  { label: "Narsingdi", value: "Narsingdi" },
  { label: "Natore", value: "Natore" },
  { label: "Netrokona", value: "Netrokona" },
  { label: "Nilphamari", value: "Nilphamari" },
  { label: "Noakhali", value: "Noakhali" },
  { label: "Pabna", value: "Pabna" },
  { label: "Panchagarh", value: "Panchagarh" },
  { label: "Patuakhali", value: "Patuakhali" },
  { label: "Pirojpur", value: "Pirojpur" },
  { label: "Rajbari", value: "Rajbari" },
  { label: "Rajshahi", value: "Rajshahi" },
  { label: "Rangamati", value: "Rangamati" },
  { label: "Rangpur", value: "Rangpur" },
  { label: "Satkhira", value: "Satkhira" },
  { label: "Shariatpur", value: "Shariatpur" },
  { label: "Sherpur", value: "Sherpur" },
  { label: "Sirajganj", value: "Sirajganj" },
  { label: "Sunamganj", value: "Sunamganj" },
  { label: "Sylhet", value: "Sylhet" },
  { label: "Tangail", value: "Tangail" },
  { label: "Thakurgaon", value: "Thakurgaon" },
];
